/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'id' : string,
  'name' : string,
  'read' : boolean,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface Donation {
  'id' : string,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export interface Event {
  'id' : string,
  'status' : string,
  'title' : string,
  'venue' : string,
  'date' : bigint,
  'publishedAt' : bigint,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'displayOrder' : bigint,
  'visible' : boolean,
  'category' : string,
  'image' : ExternalBlob,
  'altText' : string,
}
export interface ImpactStory {
  'id' : string,
  'title' : string,
  'published' : boolean,
  'story' : string,
  'image' : [] | [ExternalBlob],
}
export type Principal = Principal;
export interface Program {
  'id' : string,
  'title' : string,
  'description' : string,
  'outcomes' : Array<string>,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'objectives' : Array<string>,
}
export interface SiteSettings {
  'backgroundColor' : string,
  'footerLinks' : Array<SiteSettingsLink>,
  'primaryColor' : string,
  'logo' : [] | [ExternalBlob],
  'headerLinks' : Array<SiteSettingsLink>,
  'socialMediaLinks' : Array<SiteSettingsLink>,
  'newsletterSignupText' : string,
  'headerSlogan' : string,
  'fontFamily' : string,
  'secondaryColor' : string,
  'copyright' : string,
  'footerText' : string,
}
export interface SiteSettingsLink {
  'url' : string,
  'order' : bigint,
  'icon' : string,
  'text' : string,
}
export interface TeamMember {
  'id' : string,
  'bio' : string,
  'displayOrder' : bigint,
  'name' : string,
  'role' : string,
  'visible' : boolean,
  'photo' : [] | [ExternalBlob],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addDonation' : ActorMethod<[string, number, string], Donation>,
  'addEvent' : ActorMethod<
    [string, bigint, string, string, string, [] | [ExternalBlob], string],
    [] | [Event]
  >,
  'addFooterLink' : ActorMethod<
    [{ 'url' : string, 'order' : bigint, 'icon' : string, 'text' : string }],
    undefined
  >,
  'addGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob, bigint],
    [] | [GalleryItem]
  >,
  'addHeaderLink' : ActorMethod<
    [{ 'url' : string, 'order' : bigint, 'icon' : string, 'text' : string }],
    undefined
  >,
  'addImpactStory' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    [] | [ImpactStory]
  >,
  'addProgram' : ActorMethod<
    [string, string, string, Array<string>, Array<string>, [] | [ExternalBlob]],
    [] | [Program]
  >,
  'addSocialMediaLink' : ActorMethod<
    [{ 'url' : string, 'order' : bigint, 'icon' : string, 'text' : string }],
    undefined
  >,
  'addTeamMember' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], bigint],
    [] | [TeamMember]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'associateEmailWithPrincipal' : ActorMethod<[string, Principal], undefined>,
  'deleteContactForm' : ActorMethod<[string], boolean>,
  'deleteEvent' : ActorMethod<[string], boolean>,
  'deleteGalleryItem' : ActorMethod<[bigint], boolean>,
  'deleteImpactStory' : ActorMethod<[string], boolean>,
  'deleteProgram' : ActorMethod<[string], boolean>,
  'deleteTeamMember' : ActorMethod<[string], boolean>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllGalleryItemsAdmin' : ActorMethod<[], Array<GalleryItem>>,
  'getAllImpactStories' : ActorMethod<[], Array<ImpactStory>>,
  'getAllImpactStoriesAdmin' : ActorMethod<[], Array<ImpactStory>>,
  'getAllPrograms' : ActorMethod<[], Array<Program>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAllTeamMembersAdmin' : ActorMethod<[], Array<TeamMember>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalPastEvents' : bigint,
      'totalEvents' : bigint,
      'totalContactForms' : bigint,
      'totalTeamMembers' : bigint,
      'totalImpactStories' : bigint,
      'totalPrograms' : bigint,
      'totalDonations' : bigint,
      'totalUpcomingEvents' : bigint,
    }
  >,
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  'getEventByYear' : ActorMethod<[bigint], Array<Event>>,
  'getGalleryItem' : ActorMethod<[bigint], [] | [GalleryItem]>,
  'getGalleryItemsByCategory' : ActorMethod<[string], Array<GalleryItem>>,
  'getPastEvents' : ActorMethod<[], Array<Event>>,
  'getProgram' : ActorMethod<[string], [] | [Program]>,
  'getProgramsByCategory' : ActorMethod<[string], Array<Program>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminRoleByEmail' : ActorMethod<[string, Principal], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markContactFormAsRead' : ActorMethod<[string, boolean], boolean>,
  'registerEmail' : ActorMethod<[string], undefined>,
  'removeFooterLink' : ActorMethod<[bigint], undefined>,
  'removeHeaderLink' : ActorMethod<[bigint], undefined>,
  'removeSocialMediaLink' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], ContactForm>,
  'updateEvent' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      [] | [ExternalBlob],
      string,
    ],
    [] | [Event]
  >,
  'updateGalleryItem' : ActorMethod<
    [bigint, string, string, string, ExternalBlob, bigint, boolean],
    [] | [GalleryItem]
  >,
  'updateImpactStory' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], boolean],
    [] | [ImpactStory]
  >,
  'updateProgram' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      [] | [ExternalBlob],
    ],
    [] | [Program]
  >,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'updateTeamMember' : ActorMethod<
    [string, string, string, string, [] | [ExternalBlob], bigint, boolean],
    [] | [TeamMember]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];