/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Donation = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Event = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'date' : IDL.Int,
  'publishedAt' : IDL.Int,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'visible' : IDL.Bool,
  'category' : IDL.Text,
  'image' : ExternalBlob,
  'altText' : IDL.Text,
});
export const ImpactStory = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'story' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const Program = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'outcomes' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'objectives' : IDL.Vec(IDL.Text),
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'visible' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Principal = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactForm = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'read' : IDL.Bool,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteSettingsLink = IDL.Record({
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'text' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'backgroundColor' : IDL.Text,
  'footerLinks' : IDL.Vec(SiteSettingsLink),
  'primaryColor' : IDL.Text,
  'logo' : IDL.Opt(ExternalBlob),
  'headerLinks' : IDL.Vec(SiteSettingsLink),
  'socialMediaLinks' : IDL.Vec(SiteSettingsLink),
  'newsletterSignupText' : IDL.Text,
  'headerSlogan' : IDL.Text,
  'fontFamily' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'copyright' : IDL.Text,
  'footerText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDonation' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [Donation], []),
  'addEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Opt(Event)],
      [],
    ),
  'addFooterLink' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'order' : IDL.Nat,
          'icon' : IDL.Text,
          'text' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [IDL.Opt(GalleryItem)],
      [],
    ),
  'addHeaderLink' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'order' : IDL.Nat,
          'icon' : IDL.Text,
          'text' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'addImpactStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Opt(ImpactStory)],
      [],
    ),
  'addProgram' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Opt(Program)],
      [],
    ),
  'addSocialMediaLink' : IDL.Func(
      [
        IDL.Record({
          'url' : IDL.Text,
          'order' : IDL.Nat,
          'icon' : IDL.Text,
          'text' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat],
      [IDL.Opt(TeamMember)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([Principal, UserRole], [], []),
  'associateEmailWithPrincipal' : IDL.Func([IDL.Text, Principal], [], []),
  'deleteContactForm' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteImpactStory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteProgram' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllGalleryItemsAdmin' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllImpactStories' : IDL.Func([], [IDL.Vec(ImpactStory)], ['query']),
  'getAllImpactStoriesAdmin' : IDL.Func([], [IDL.Vec(ImpactStory)], ['query']),
  'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getAllTeamMembersAdmin' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPastEvents' : IDL.Nat,
          'totalEvents' : IDL.Nat,
          'totalContactForms' : IDL.Nat,
          'totalTeamMembers' : IDL.Nat,
          'totalImpactStories' : IDL.Nat,
          'totalPrograms' : IDL.Nat,
          'totalDonations' : IDL.Nat,
          'totalUpcomingEvents' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getEventByYear' : IDL.Func([IDL.Int], [IDL.Vec(Event)], ['query']),
  'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
  'getGalleryItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getProgram' : IDL.Func([IDL.Text], [IDL.Opt(Program)], ['query']),
  'getProgramsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'grantAdminRoleByEmail' : IDL.Func([IDL.Text, Principal], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markContactFormAsRead' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'registerEmail' : IDL.Func([IDL.Text], [], []),
  'removeFooterLink' : IDL.Func([IDL.Nat], [], []),
  'removeHeaderLink' : IDL.Func([IDL.Nat], [], []),
  'removeSocialMediaLink' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ContactForm],
      [],
    ),
  'updateEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Opt(Event)],
      [],
    ),
  'updateGalleryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat, IDL.Bool],
      [IDL.Opt(GalleryItem)],
      [],
    ),
  'updateImpactStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [IDL.Opt(ImpactStory)],
      [],
    ),
  'updateProgram' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Opt(Program)],
      [],
    ),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  'updateTeamMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Nat,
        IDL.Bool,
      ],
      [IDL.Opt(TeamMember)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Donation = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Event = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'date' : IDL.Int,
    'publishedAt' : IDL.Int,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'visible' : IDL.Bool,
    'category' : IDL.Text,
    'image' : ExternalBlob,
    'altText' : IDL.Text,
  });
  const ImpactStory = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'story' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Program = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'outcomes' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'objectives' : IDL.Vec(IDL.Text),
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'visible' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Principal = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactForm = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'read' : IDL.Bool,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteSettingsLink = IDL.Record({
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'text' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'backgroundColor' : IDL.Text,
    'footerLinks' : IDL.Vec(SiteSettingsLink),
    'primaryColor' : IDL.Text,
    'logo' : IDL.Opt(ExternalBlob),
    'headerLinks' : IDL.Vec(SiteSettingsLink),
    'socialMediaLinks' : IDL.Vec(SiteSettingsLink),
    'newsletterSignupText' : IDL.Text,
    'headerSlogan' : IDL.Text,
    'fontFamily' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'copyright' : IDL.Text,
    'footerText' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDonation' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [Donation], []),
    'addEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Opt(Event)],
        [],
      ),
    'addFooterLink' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'order' : IDL.Nat,
            'icon' : IDL.Text,
            'text' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [IDL.Opt(GalleryItem)],
        [],
      ),
    'addHeaderLink' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'order' : IDL.Nat,
            'icon' : IDL.Text,
            'text' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'addImpactStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Opt(ImpactStory)],
        [],
      ),
    'addProgram' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Opt(Program)],
        [],
      ),
    'addSocialMediaLink' : IDL.Func(
        [
          IDL.Record({
            'url' : IDL.Text,
            'order' : IDL.Nat,
            'icon' : IDL.Text,
            'text' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Nat],
        [IDL.Opt(TeamMember)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([Principal, UserRole], [], []),
    'associateEmailWithPrincipal' : IDL.Func([IDL.Text, Principal], [], []),
    'deleteContactForm' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteImpactStory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteProgram' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllGalleryItemsAdmin' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllImpactStories' : IDL.Func([], [IDL.Vec(ImpactStory)], ['query']),
    'getAllImpactStoriesAdmin' : IDL.Func(
        [],
        [IDL.Vec(ImpactStory)],
        ['query'],
      ),
    'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getAllTeamMembersAdmin' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPastEvents' : IDL.Nat,
            'totalEvents' : IDL.Nat,
            'totalContactForms' : IDL.Nat,
            'totalTeamMembers' : IDL.Nat,
            'totalImpactStories' : IDL.Nat,
            'totalPrograms' : IDL.Nat,
            'totalDonations' : IDL.Nat,
            'totalUpcomingEvents' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getEventByYear' : IDL.Func([IDL.Int], [IDL.Vec(Event)], ['query']),
    'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
    'getGalleryItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getProgram' : IDL.Func([IDL.Text], [IDL.Opt(Program)], ['query']),
    'getProgramsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Program)],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'grantAdminRoleByEmail' : IDL.Func([IDL.Text, Principal], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markContactFormAsRead' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'registerEmail' : IDL.Func([IDL.Text], [], []),
    'removeFooterLink' : IDL.Func([IDL.Nat], [], []),
    'removeHeaderLink' : IDL.Func([IDL.Nat], [], []),
    'removeSocialMediaLink' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ContactForm],
        [],
      ),
    'updateEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Opt(Event)],
        [],
      ),
    'updateGalleryItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Opt(GalleryItem)],
        [],
      ),
    'updateImpactStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [IDL.Opt(ImpactStory)],
        [],
      ),
    'updateProgram' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Opt(Program)],
        [],
      ),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
    'updateTeamMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Opt(TeamMember)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };