/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactForm {
    id: string;
    name: string;
    read: boolean;
    submittedAt: bigint;
    email: string;
    message: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    id: string;
    status: string;
    title: string;
    venue: string;
    date: bigint;
    publishedAt: bigint;
    description: string;
    image?: ExternalBlob;
    location: string;
}
export type Principal = Principal;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SiteSettings {
    backgroundColor: string;
    footerLinks: Array<SiteSettingsLink>;
    primaryColor: string;
    headerLogo?: ExternalBlob;
    headerLinks: Array<SiteSettingsLink>;
    socialMediaLinks: Array<SiteSettingsLink>;
    newsletterSignupText: string;
    headerSlogan: string;
    fontFamily: string;
    secondaryColor: string;
    copyright: string;
    footerText: string;
}
export interface Donation {
    id: string;
    name: string;
    message: string;
    timestamp: bigint;
    amount: number;
}
export interface SiteSettingsLink {
    url: string;
    order: bigint;
    icon: string;
    text: string;
}
export interface Program {
    id: string;
    title: string;
    description: string;
    outcomes: Array<string>;
    category: string;
    image?: ExternalBlob;
    objectives: Array<string>;
}
export interface TeamMember {
    id: string;
    bio: string;
    displayOrder: bigint;
    name: string;
    role: string;
    visible: boolean;
    photo?: ExternalBlob;
}
export interface GalleryItem {
    id: bigint;
    title: string;
    displayOrder: bigint;
    visible: boolean;
    category: string;
    image: ExternalBlob;
    altText: string;
}
export interface ImpactStory {
    id: string;
    title: string;
    published: boolean;
    story: string;
    image?: ExternalBlob;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addDonation(name: string, amount: number, message: string): Promise<Donation>;
    addEvent(title: string, date: bigint, location: string, description: string, status: string, image: ExternalBlob | null, venue: string): Promise<Event | null>;
    addFooterLink(newLink: {
        url: string;
        order: bigint;
        icon: string;
        text: string;
    }): Promise<void>;
    addGalleryItem(title: string, altText: string, category: string, image: ExternalBlob, displayOrder: bigint): Promise<GalleryItem | null>;
    addHeaderLink(newLink: {
        url: string;
        order: bigint;
        icon: string;
        text: string;
    }): Promise<void>;
    addImpactStory(title: string, story: string, image: ExternalBlob | null): Promise<ImpactStory | null>;
    addProgram(title: string, description: string, category: string, objectives: Array<string>, outcomes: Array<string>, image: ExternalBlob | null): Promise<Program | null>;
    addSocialMediaLink(newLink: {
        url: string;
        order: bigint;
        icon: string;
        text: string;
    }): Promise<void>;
    addTeamMember(name: string, role: string, bio: string, photo: ExternalBlob | null, displayOrder: bigint): Promise<TeamMember | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    associateEmailWithPrincipal(email: string, principal: Principal): Promise<void>;
    deleteContactForm(id: string): Promise<boolean>;
    deleteEvent(id: string): Promise<boolean>;
    deleteGalleryItem(id: bigint): Promise<boolean>;
    deleteImpactStory(id: string): Promise<boolean>;
    deleteProgram(id: string): Promise<boolean>;
    deleteTeamMember(id: string): Promise<boolean>;
    getAllContactForms(): Promise<Array<ContactForm>>;
    getAllDonations(): Promise<Array<Donation>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllGalleryItems(): Promise<Array<GalleryItem>>;
    getAllGalleryItemsAdmin(): Promise<Array<GalleryItem>>;
    getAllImpactStories(): Promise<Array<ImpactStory>>;
    getAllImpactStoriesAdmin(): Promise<Array<ImpactStory>>;
    getAllPrograms(): Promise<Array<Program>>;
    getAllTeamMembers(): Promise<Array<TeamMember>>;
    getAllTeamMembersAdmin(): Promise<Array<TeamMember>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        totalPastEvents: bigint;
        totalEvents: bigint;
        totalContactForms: bigint;
        totalTeamMembers: bigint;
        totalImpactStories: bigint;
        totalPrograms: bigint;
        totalDonations: bigint;
        totalUpcomingEvents: bigint;
    }>;
    getEvent(id: string): Promise<Event | null>;
    getEventByYear(year: bigint): Promise<Array<Event>>;
    getGalleryItem(id: bigint): Promise<GalleryItem | null>;
    getGalleryItemsByCategory(category: string): Promise<Array<GalleryItem>>;
    getPastEvents(): Promise<Array<Event>>;
    getProgram(id: string): Promise<Program | null>;
    getProgramsByCategory(category: string): Promise<Array<Program>>;
    getSiteSettings(): Promise<SiteSettings>;
    getUpcomingEvents(): Promise<Array<Event>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantAdminRoleByEmail(email: string, emailPrincipal: Principal): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markContactFormAsRead(id: string, read: boolean): Promise<boolean>;
    registerEmail(email: string): Promise<void>;
    removeFooterLink(index: bigint): Promise<void>;
    removeHeaderLink(index: bigint): Promise<void>;
    removeSocialMediaLink(index: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactForm(name: string, email: string, message: string): Promise<ContactForm>;
    updateEvent(id: string, title: string, date: bigint, location: string, description: string, status: string, image: ExternalBlob | null, venue: string): Promise<Event | null>;
    updateGalleryItem(id: bigint, title: string, altText: string, category: string, image: ExternalBlob, displayOrder: bigint, visible: boolean): Promise<GalleryItem | null>;
    updateImpactStory(id: string, title: string, story: string, image: ExternalBlob | null, published: boolean): Promise<ImpactStory | null>;
    updateProgram(id: string, title: string, description: string, category: string, objectives: Array<string>, outcomes: Array<string>, image: ExternalBlob | null): Promise<Program | null>;
    updateSiteSettings(newSettings: SiteSettings): Promise<void>;
    updateTeamMember(id: string, name: string, role: string, bio: string, photo: ExternalBlob | null, displayOrder: bigint, visible: boolean): Promise<TeamMember | null>;
}
import type { Event as _Event, ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, ImpactStory as _ImpactStory, Program as _Program, SiteSettings as _SiteSettings, SiteSettingsLink as _SiteSettingsLink, TeamMember as _TeamMember, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addDonation(arg0: string, arg1: number, arg2: string): Promise<Donation> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonation(arg0, arg1, arg2);
            return result;
        }
    }
    async addEvent(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: ExternalBlob | null, arg6: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFooterLink(arg0: {
        url: string;
        order: bigint;
        icon: string;
        text: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFooterLink(arg0);
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: bigint): Promise<GalleryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async addHeaderLink(arg0: {
        url: string;
        order: bigint;
        icon: string;
        text: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeaderLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeaderLink(arg0);
            return result;
        }
    }
    async addImpactStory(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<ImpactStory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addImpactStory(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImpactStory(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProgram(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: Array<string>, arg5: ExternalBlob | null): Promise<Program | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addProgram(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProgram(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSocialMediaLink(arg0: {
        url: string;
        order: bigint;
        icon: string;
        text: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSocialMediaLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSocialMediaLink(arg0);
            return result;
        }
    }
    async addTeamMember(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: bigint): Promise<TeamMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamMember(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamMember(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async associateEmailWithPrincipal(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.associateEmailWithPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.associateEmailWithPrincipal(arg0, arg1);
            return result;
        }
    }
    async deleteContactForm(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactForm(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deleteImpactStory(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImpactStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImpactStory(arg0);
            return result;
        }
    }
    async deleteProgram(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProgram(arg0);
            return result;
        }
    }
    async deleteTeamMember(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return result;
        }
    }
    async getAllContactForms(): Promise<Array<ContactForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactForms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactForms();
            return result;
        }
    }
    async getAllDonations(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonations();
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryItems();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryItems();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGalleryItemsAdmin(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryItemsAdmin();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryItemsAdmin();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllImpactStories(): Promise<Array<ImpactStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImpactStories();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImpactStories();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllImpactStoriesAdmin(): Promise<Array<ImpactStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImpactStoriesAdmin();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImpactStoriesAdmin();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrograms(): Promise<Array<Program>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrograms();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrograms();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamMembers();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamMembers();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamMembersAdmin(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamMembersAdmin();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamMembersAdmin();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        totalPastEvents: bigint;
        totalEvents: bigint;
        totalContactForms: bigint;
        totalTeamMembers: bigint;
        totalImpactStories: bigint;
        totalPrograms: bigint;
        totalDonations: bigint;
        totalUpcomingEvents: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getEvent(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventByYear(arg0: bigint): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventByYear(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventByYear(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryItem(arg0: bigint): Promise<GalleryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItem(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItem(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryItemsByCategory(arg0: string): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItemsByCategory(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItemsByCategory(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPastEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPastEvents();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPastEvents();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgram(arg0: string): Promise<Program | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgram(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgram(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgramsByCategory(arg0: string): Promise<Array<Program>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgramsByCategory(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgramsByCategory(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return from_candid_SiteSettings_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return from_candid_SiteSettings_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantAdminRoleByEmail(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantAdminRoleByEmail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantAdminRoleByEmail(arg0, arg1);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markContactFormAsRead(arg0: string, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactFormAsRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactFormAsRead(arg0, arg1);
            return result;
        }
    }
    async registerEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerEmail(arg0);
            return result;
        }
    }
    async removeFooterLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFooterLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFooterLink(arg0);
            return result;
        }
    }
    async removeHeaderLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHeaderLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHeaderLink(arg0);
            return result;
        }
    }
    async removeSocialMediaLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSocialMediaLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSocialMediaLink(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<ContactForm> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async updateEvent(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: ExternalBlob | null, arg7: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGalleryItem(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob, arg5: bigint, arg6: boolean): Promise<GalleryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryItem(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryItem(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateImpactStory(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: boolean): Promise<ImpactStory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImpactStory(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImpactStory(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProgram(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>, arg5: Array<string>, arg6: ExternalBlob | null): Promise<Program | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgram(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgram(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSiteSettings(arg0: SiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(await to_candid_SiteSettings_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(await to_candid_SiteSettings_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTeamMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob | null, arg5: bigint, arg6: boolean): Promise<TeamMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_Event_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ImpactStory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImpactStory): Promise<ImpactStory> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Program_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Program): Promise<Program> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_SiteSettings_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteSettings): Promise<SiteSettings> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_TeamMember_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): Promise<TeamMember> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Promise<Event | null> {
    return value.length === 0 ? null : await from_candid_Event_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryItem]): Promise<GalleryItem | null> {
    return value.length === 0 ? null : await from_candid_GalleryItem_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImpactStory]): Promise<ImpactStory | null> {
    return value.length === 0 ? null : await from_candid_ImpactStory_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Program]): Promise<Program | null> {
    return value.length === 0 ? null : await from_candid_Program_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMember]): Promise<TeamMember | null> {
    return value.length === 0 ? null : await from_candid_TeamMember_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    title: string;
    venue: string;
    date: bigint;
    publishedAt: bigint;
    description: string;
    image: [] | [_ExternalBlob];
    location: string;
}): Promise<{
    id: string;
    status: string;
    title: string;
    venue: string;
    date: bigint;
    publishedAt: bigint;
    description: string;
    image?: ExternalBlob;
    location: string;
}> {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        venue: value.venue,
        date: value.date,
        publishedAt: value.publishedAt,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.image)),
        location: value.location
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    displayOrder: bigint;
    visible: boolean;
    category: string;
    image: _ExternalBlob;
    altText: string;
}): Promise<{
    id: bigint;
    title: string;
    displayOrder: bigint;
    visible: boolean;
    category: string;
    image: ExternalBlob;
    altText: string;
}> {
    return {
        id: value.id,
        title: value.title,
        displayOrder: value.displayOrder,
        visible: value.visible,
        category: value.category,
        image: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.image),
        altText: value.altText
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    published: boolean;
    story: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    title: string;
    published: boolean;
    story: string;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        published: value.published,
        story: value.story,
        image: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    outcomes: Array<string>;
    category: string;
    image: [] | [_ExternalBlob];
    objectives: Array<string>;
}): Promise<{
    id: string;
    title: string;
    description: string;
    outcomes: Array<string>;
    category: string;
    image?: ExternalBlob;
    objectives: Array<string>;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        outcomes: value.outcomes,
        category: value.category,
        image: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.image)),
        objectives: value.objectives
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    displayOrder: bigint;
    name: string;
    role: string;
    visible: boolean;
    photo: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    bio: string;
    displayOrder: bigint;
    name: string;
    role: string;
    visible: boolean;
    photo?: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: value.bio,
        displayOrder: value.displayOrder,
        name: value.name,
        role: value.role,
        visible: value.visible,
        photo: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.photo))
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundColor: string;
    footerLinks: Array<_SiteSettingsLink>;
    primaryColor: string;
    headerLogo: [] | [_ExternalBlob];
    headerLinks: Array<_SiteSettingsLink>;
    socialMediaLinks: Array<_SiteSettingsLink>;
    newsletterSignupText: string;
    headerSlogan: string;
    fontFamily: string;
    secondaryColor: string;
    copyright: string;
    footerText: string;
}): Promise<{
    backgroundColor: string;
    footerLinks: Array<SiteSettingsLink>;
    primaryColor: string;
    headerLogo?: ExternalBlob;
    headerLinks: Array<SiteSettingsLink>;
    socialMediaLinks: Array<SiteSettingsLink>;
    newsletterSignupText: string;
    headerSlogan: string;
    fontFamily: string;
    secondaryColor: string;
    copyright: string;
    footerText: string;
}> {
    return {
        backgroundColor: value.backgroundColor,
        footerLinks: value.footerLinks,
        primaryColor: value.primaryColor,
        headerLogo: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.headerLogo)),
        headerLinks: value.headerLinks,
        socialMediaLinks: value.socialMediaLinks,
        newsletterSignupText: value.newsletterSignupText,
        headerSlogan: value.headerSlogan,
        fontFamily: value.fontFamily,
        secondaryColor: value.secondaryColor,
        copyright: value.copyright,
        footerText: value.footerText
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImpactStory>): Promise<Array<ImpactStory>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ImpactStory_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Program>): Promise<Array<Program>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Program_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Promise<Array<TeamMember>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TeamMember_n25(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_SiteSettings_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteSettings): Promise<_SiteSettings> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundColor: string;
    footerLinks: Array<SiteSettingsLink>;
    primaryColor: string;
    headerLogo?: ExternalBlob;
    headerLinks: Array<SiteSettingsLink>;
    socialMediaLinks: Array<SiteSettingsLink>;
    newsletterSignupText: string;
    headerSlogan: string;
    fontFamily: string;
    secondaryColor: string;
    copyright: string;
    footerText: string;
}): Promise<{
    backgroundColor: string;
    footerLinks: Array<_SiteSettingsLink>;
    primaryColor: string;
    headerLogo: [] | [_ExternalBlob];
    headerLinks: Array<_SiteSettingsLink>;
    socialMediaLinks: Array<_SiteSettingsLink>;
    newsletterSignupText: string;
    headerSlogan: string;
    fontFamily: string;
    secondaryColor: string;
    copyright: string;
    footerText: string;
}> {
    return {
        backgroundColor: value.backgroundColor,
        footerLinks: value.footerLinks,
        primaryColor: value.primaryColor,
        headerLogo: value.headerLogo ? candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value.headerLogo)) : candid_none(),
        headerLinks: value.headerLinks,
        socialMediaLinks: value.socialMediaLinks,
        newsletterSignupText: value.newsletterSignupText,
        headerSlogan: value.headerSlogan,
        fontFamily: value.fontFamily,
        secondaryColor: value.secondaryColor,
        copyright: value.copyright,
        footerText: value.footerText
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
